### ISSUE TITLE
demo does not work 

### ISSUE THREAD

**Issue by ShaodongWei** [PratheepaJ/bootLong#1]
Hello!   
I think in the "The block bootstrap method" section of your demo is not working. The issue seems because you name parameters differently, therefore following functions do not recognize?

**Comment by PratheepaJ** [comment]
Thanks for raising the issue. I have updated the demo yesterday. Did you try after that?
You will need to reinstall bootLong as i made an extensive revision.
Let me know if does help now.

Best,
Pratheepa



On Sep 18, 2018, at 4:29 AM, ShaodongWei <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello!
I think in the "The block bootstrap method" section of your demo is not working. The issue seems because you name parameters differently, therefore following functions do not recognize?

**Comment by ShaodongWei** [comment]
Oh yes, it is fixed now after reinstall the package. I am playing with it. Thanks !

Best
Shaodong

On 18 Sep 2018, at 16.14, Pratheepa Jeganathan <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for raising the issue. I have updated the demo yesterday. Did you try after that?
You will need to reinstall bootLong as i made an extensive revision.
Let me know if does help now.

Best,
Pratheepa



On Sep 18, 2018, at 4:29 AM, ShaodongWei <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hello!
I think in the "The block bootstrap method" section of your demo is not working. The issue seems because you name parameters differently, therefore following functions do not recognize?

**Comment by PratheepaJ** [comment]
Thanks for trying it.
I’m looking forward to hearing any issues.

Best,
Pratheepa



On Sep 18, 2018, at 8:07 AM, ShaodongWei <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh yes, it is fixed now after reinstall the package. I am playing with it. Thanks !

Best
Shaodong

On 18 Sep 2018, at 16.14, Pratheepa Jeganathan <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Thanks for raising the issue. I have updated the demo yesterday. Did you try after that?
You will need to reinstall bootLong as i made an extensive revision.
Let me know if does help now.

Best,
Pratheepa



On Sep 18, 2018, at 4:29 AM, ShaodongWei <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hello!
I think in the "The block bootstrap method" section of your demo is not working. The issue seems because you name parameters differently, therefore following functions do not recognize?

**Comment by PratheepaJ** [comment]
Closing issue #1 as it has been fixed.
